// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Calculator.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Calculator {
  public static partial class Calculator
  {
    static readonly string __ServiceName = "Calculator.Calculator";

    static readonly grpc::Marshaller<global::Calculator.CalculateRequest> __Marshaller_CalculateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Calculator.CalculateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Calculator.CalculateReply> __Marshaller_CalculateReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Calculator.CalculateReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Calculator.CalculateRequest, global::Calculator.CalculateReply> __Method_Add = new grpc::Method<global::Calculator.CalculateRequest, global::Calculator.CalculateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Add",
        __Marshaller_CalculateRequest,
        __Marshaller_CalculateReply);

    static readonly grpc::Method<global::Calculator.CalculateRequest, global::Calculator.CalculateReply> __Method_Subtract = new grpc::Method<global::Calculator.CalculateRequest, global::Calculator.CalculateReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Subtract",
        __Marshaller_CalculateRequest,
        __Marshaller_CalculateReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Calculator.CalculatorReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Calculator</summary>
    public abstract partial class CalculatorBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Calculator.CalculateReply> Add(global::Calculator.CalculateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Calculator.CalculateReply> Subtract(global::Calculator.CalculateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Calculator</summary>
    public partial class CalculatorClient : grpc::ClientBase<CalculatorClient>
    {
      /// <summary>Creates a new client for Calculator</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CalculatorClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Calculator that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CalculatorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CalculatorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CalculatorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Calculator.CalculateReply Add(global::Calculator.CalculateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Add(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Calculator.CalculateReply Add(global::Calculator.CalculateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Add, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Calculator.CalculateReply> AddAsync(global::Calculator.CalculateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Calculator.CalculateReply> AddAsync(global::Calculator.CalculateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Add, null, options, request);
      }
      public virtual global::Calculator.CalculateReply Subtract(global::Calculator.CalculateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Subtract(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Calculator.CalculateReply Subtract(global::Calculator.CalculateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Subtract, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Calculator.CalculateReply> SubtractAsync(global::Calculator.CalculateRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubtractAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Calculator.CalculateReply> SubtractAsync(global::Calculator.CalculateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Subtract, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CalculatorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CalculatorClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CalculatorBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Add, serviceImpl.Add)
          .AddMethod(__Method_Subtract, serviceImpl.Subtract).Build();
    }

  }
}
#endregion
